apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo-app.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType | default "ClusterIP" }}
  selector:
    {{- include "todo-app.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.ports.frontend }}
      targetPort: {{ .Values.ports.frontend }}
      protocol: TCP
