# Redpanda Cloud SASL credentials secret for Dapr Pub/Sub
{{- if .Values.dapr.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: redpanda-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.dapr.redpanda.brokers }}
  REDPANDA_BROKERS: {{ .Values.dapr.redpanda.brokers | b64enc | quote }}
  {{- else }}
  REDPANDA_BROKERS: {{ "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.dapr.redpanda.username }}
  REDPANDA_SASL_USERNAME: {{ .Values.dapr.redpanda.username | b64enc | quote }}
  {{- else }}
  REDPANDA_SASL_USERNAME: {{ "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.dapr.redpanda.password }}
  REDPANDA_SASL_PASSWORD: {{ .Values.dapr.redpanda.password | b64enc | quote }}
  {{- else }}
  REDPANDA_SASL_PASSWORD: {{ "" | b64enc | quote }}
  {{- end }}
{{- end }}
